### PR TITLE
Alignment on the content of the button.

### PR DESCRIPTION
**Pull request by thruthesky**
I believe other developers also need the alignment of icon and text.
I have edited
- main.dart for example
- auth_button_style.dart
- button_content.dart
for adding the mainAxisSize and mainAxisAlignment.

image

Example of use. See the mainAxisSize and mainAxisAlignment.

```dart
AppleAuthButton(
  onPressed: () {
    // your implementation
    setState(() {
      isLoading = !isLoading;
    });
  },
  themeMode: themeMode,
  isLoading: isLoading,
  style: AuthButtonStyle(
    width: double.infinity,
    buttonType: buttonType,
    iconType: iconType,
    margin: const EdgeInsets.only(left: 24, right: 24, bottom: 8),
    mainAxisSize: MainAxisSize.max,
    mainAxisAlignment: MainAxisAlignment.start,
  ),
),
FacebookAuthButton(
  onPressed: () {
    // your implementation
    setState(() {
      isLoading = !isLoading;
    });
  },
  themeMode: themeMode,
  isLoading: isLoading,
  style: AuthButtonStyle(
    width: double.infinity,
    buttonType: buttonType,
    iconType: iconType,
    margin: const EdgeInsets.only(left: 24, right: 24, bottom: 18),
    mainAxisSize: MainAxisSize.max,
    mainAxisAlignment: MainAxisAlignment.start,
  ),
),
```

### CODE REVIEW

**Comment by elbeicktalat** [comment]
Hi @thruthesky nice job,
probably they would like, I'll check for other properties to add.

**Comment by fryette** [comment]
@elbeicktalat any chance to merge it?

**Comment by azeunkn0wn** [comment]
please add this.

**Comment by elbeicktalat** [comment]
@thruthesky Thanks for your contribution,
but I'm not going to merge your code since there are too much non related changes.

Such as formatting and adding platform code to git. Anyway this issue has been solved in #60

**Pull request closed without merging**
